baseurl = "https://mike-neko.github.io/"
languageCode = "jp"
title = "M.Ikeの小ネタ集"

disqusShortname = "" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "M.Ike"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:slug/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    tag = "tags"
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = ""
    defaultKeywords = ""

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d layout-reverse"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "xcode"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "〜小ネタ集〜"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Tips"

    # Metadata used to drive integrations.
    googleAuthorship = ""
    googleAnalytics = "UA-83211342-1"
    gravatarHash = ""

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/mike-neko"
    bitbucket = ""
    stackOverflow = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/m__ike_"
    youtube = ""
    instagram = "https://www.instagram.com/m_ike__/"

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link

